import type { WorkflowDesign, WorkflowDesignPhase, WorkflowDesignStep } from './types/workflow';

/** 与 workflow 运行时 MAX_AGENTS 一致 */
const MAX_STEPS = 32;
const AGENT_TYPE_RE = /^[A-Za-z0-9][A-Za-z0-9_:-]{0,127}$/;
const ARG_KEY_RE = /^[A-Za-z_][A-Za-z0-9_]{0,31}$/;
const PLACEHOLDER_RE = /\{\{\s*(?:args\.([A-Za-z_][A-Za-z0-9_]{0,31})|(prev))\s*\}\}/g;

function text(value: unknown, max: number): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed && trimmed.length <= max ? trimmed : null;
}

export type PlaceholderToken =
  | { kind: 'arg'; key: string; token: string }
  | { kind: 'prev'; token: string };

/** 可插入提示词的占位符；第一个阶段没有上一阶段输出 */
export function placeholderTokens(
  argKeys: readonly string[],
  phaseIndex: number
): PlaceholderToken[] {
  const tokens: PlaceholderToken[] = [...new Set(argKeys)]
    .filter((key) => ARG_KEY_RE.test(key))
    .map((key) => ({ kind: 'arg', key, token: `{{args.${key}}}` }));
  if (phaseIndex > 0) tokens.push({ kind: 'prev', token: '{{prev}}' });
  return tokens;
}

/** 在光标/选区处插入，返回插入后的光标位置 */
export function insertPlaceholder(
  value: string,
  selectionStart: number,
  selectionEnd: number,
  token: string
): { text: string; cursor: number } {
  const start = Math.min(Math.max(selectionStart, 0), value.length);
  const end = Math.min(Math.max(selectionEnd, start), value.length);
  return { text: value.slice(0, start) + token + value.slice(end), cursor: start + token.length };
}

function parseStep(value: unknown): WorkflowDesignStep | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  const label = text(record.label, 80);
  const prompt = text(record.prompt, 8000);
  const agentType = typeof record.agentType === 'string' ? record.agentType.trim() : '';
  if (!label || !prompt || (agentType && !AGENT_TYPE_RE.test(agentType))) return null;
  return { label, agentType, prompt };
}

function parsePhase(value: unknown): WorkflowDesignPhase | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  const title = text(record.title, 80);
  if (!title || !Array.isArray(record.steps) || record.steps.length === 0) return null;
  const steps = record.steps.map(parseStep);
  return steps.every((step) => step !== null) ? { title, steps } : null;
}

/** 跨进程/文件边界收窄；任一阶段或步骤不合法整体拒绝 */
export function parseWorkflowDesign(value: unknown): WorkflowDesign | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const raw = (value as Record<string, unknown>).phases;
  if (!Array.isArray(raw) || raw.length === 0) return null;
  const phases = raw.map(parsePhase);
  if (!phases.every((phase) => phase !== null)) return null;
  const steps = phases.reduce((sum, phase) => sum + phase.steps.length, 0);
  return steps <= MAX_STEPS ? { phases } : null;
}

export type PromptPart =
  | { kind: 'text'; text: string }
  | { kind: 'arg'; key: string }
  | { kind: 'prev' };

/** 识别 `{{args.key}}` 与 `{{prev}}`；脚本生成和节点预览共用这一口径 */
export function splitPromptPlaceholders(prompt: string): PromptPart[] {
  const parts: PromptPart[] = [];
  let last = 0;
  for (const match of prompt.matchAll(PLACEHOLDER_RE)) {
    if (match.index > last) parts.push({ kind: 'text', text: prompt.slice(last, match.index) });
    parts.push(match[1] ? { kind: 'arg', key: match[1] } : { kind: 'prev' });
    last = match.index + match[0].length;
  }
  if (last < prompt.length) parts.push({ kind: 'text', text: prompt.slice(last) });
  return parts;
}

/** 参数代入、上一阶段输出代入；字面量一律 JSON 编码 */
function promptExpression(prompt: string): string {
  const parts = splitPromptPlaceholders(prompt).map((part) =>
    part.kind === 'text'
      ? JSON.stringify(part.text)
      : part.kind === 'arg'
        ? `String(args.${part.key} ?? '')`
        : 'prev'
  );
  return parts.length > 0 ? parts.join(' + ') : '""';
}

function stepCall({ label, agentType, prompt }: WorkflowDesignStep): string {
  const opts = [`label: ${JSON.stringify(label)}`];
  if (agentType) opts.push(`agentType: ${JSON.stringify(agentType)}`);
  return `  () => agent(${promptExpression(prompt)}, { ${opts.join(', ')} }),`;
}

/** 生成与手写同格式的脚本；同一设计输出稳定，读回时据此判断脚本是否被手改 */
export function generateWorkflowScript(design: WorkflowDesign): string {
  const lines = [
    '// Generated by the workflow designer. Editing this code detaches it from the designer.',
    'const collect = (labels, outputs) =>',
    "  labels.map((label, i) => '## ' + label + '\\n\\n' + (outputs[i] ?? '(failed)')).join('\\n\\n');",
    "let prev = '';",
  ];
  for (const phase of design.phases) {
    const labels = JSON.stringify(phase.steps.map((step) => step.label));
    lines.push(
      '',
      `await phase(${JSON.stringify(phase.title)});`,
      `prev = collect(${labels}, await parallel([`,
      ...phase.steps.map(stepCall),
      ']));'
    );
  }
  lines.push('', 'return prev;', '');
  return lines.join('\n');
}
